/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: person.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "person.pb-c.h"
void tutorial__person__init(Tutorial__Person* message)
{
	static const Tutorial__Person init_value = TUTORIAL__PERSON__INIT;
	*message = init_value;
}
size_t tutorial__person__get_packed_size(const Tutorial__Person* message)
{
	assert(message->base.descriptor == &tutorial__person__descriptor);
	return protobuf_c_message_get_packed_size((const ProtobufCMessage*)(message));
}
size_t tutorial__person__pack(const Tutorial__Person* message, uint8_t* out)
{
	assert(message->base.descriptor == &tutorial__person__descriptor);
	return protobuf_c_message_pack((const ProtobufCMessage*)message, out);
}
size_t tutorial__person__pack_to_buffer(const Tutorial__Person* message,
										ProtobufCBuffer* buffer)
{
	assert(message->base.descriptor == &tutorial__person__descriptor);
	return protobuf_c_message_pack_to_buffer((const ProtobufCMessage*)message, buffer);
}
Tutorial__Person* tutorial__person__unpack(ProtobufCAllocator* allocator, size_t len,
										   const uint8_t* data)
{
	return (Tutorial__Person*)protobuf_c_message_unpack(&tutorial__person__descriptor,
														allocator, len, data);
}
void tutorial__person__free_unpacked(Tutorial__Person* message,
									 ProtobufCAllocator* allocator)
{
	if (!message)
		return;
	assert(message->base.descriptor == &tutorial__person__descriptor);
	protobuf_c_message_free_unpacked((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tutorial__person__field_descriptors[2] = {
	{
		"name", 1, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_STRING,
		0, /* quantifier_offset */
		offsetof(Tutorial__Person, name), NULL, NULL, 0, /* flags */
		0, NULL, NULL /* reserved1,reserved2, etc */
	},
	{
		"id", 2, PROTOBUF_C_LABEL_REQUIRED, PROTOBUF_C_TYPE_INT32,
		0, /* quantifier_offset */
		offsetof(Tutorial__Person, id), NULL, NULL, 0, /* flags */
		0, NULL, NULL /* reserved1,reserved2, etc */
	},
};
static const unsigned tutorial__person__field_indices_by_name[] = {
	1, /* field[1] = id */
	0, /* field[0] = name */
};
static const ProtobufCIntRange tutorial__person__number_ranges[1 + 1] = { { 1, 0 },
																		  { 0, 2 } };
const ProtobufCMessageDescriptor tutorial__person__descriptor = {
	PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
	"tutorial.Person",
	"Person",
	"Tutorial__Person",
	"tutorial",
	sizeof(Tutorial__Person),
	2,
	tutorial__person__field_descriptors,
	tutorial__person__field_indices_by_name,
	1,
	tutorial__person__number_ranges,
	(ProtobufCMessageInit)tutorial__person__init,
	NULL,
	NULL,
	NULL /* reserved[123] */
};
